### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hmmxp** [frankiexyz/ping-exporter#4] opened 2017-10-14 04:21 UTC
Hi,

Running ping-exporter.py on Centos 7.4 on 1.1.1.1 and Prometheus 1.7.2 on 1.1.1.2

On 1.1.1.1 Running Ping Exporter Receiving The Following Error

Exception happened during processing of request from ('1.1.1.2', 44436)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/lis/ping-exporter.py", line 48, in do_GET
    message = '\n'.join(ping(address, False, count, size))
  File "/opt/lis/ping-exporter.py", line 18, in ping
    loss = cmd_output[1].split("%")[1].split("/")[2]
IndexError: list index out of range

I Am Running Ping Exporter via
/usr/bin/python /opt/lis/ping-exporter.py

My Configuration On Prometheus

  - job_name: 'ping_exporter'
    scrape_interval: 60s
    metrics_path: /probe
    params:
      prot: ['4']    
    static_configs:
      - targets:
        - www.google.com
        - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance    
        replacement: ${1}
      - source_labels: []
        regex: .*      
        target_label: __address__
        replacement: 1.1.1.1:8085  

How Can I Resolve or Run This Script Properly

Thank You

**Comment by frankiexyz** [comment] 2017-10-14 05:55
Hi, I believe you already installed the fping in your CentOS and I can reproduce the issue with CentOS. I believe it is due to the installation directory of fping is different than Debian/Ubuntu.
I just did a PR and merged the change (https://github.com/frankiexyz/ping-exporter/pull/5). Please let me know if the problem is resolved now.

If you are still facing an issue , please share the output of the following command. (Please change the address and port number to your own setup)
```
[root@li1772-69 ping-exporter]# curl "127.0.0.1:8085/?target=8.8.8.8"
ping_avg 1.15
ping_max 1.20
ping_min  1.08
ping_loss 0
[root@li1772-69 ping-exporter]#
```  
Thank you and have a good day!

**Comment by hmmxp** [comment] 2017-10-14 06:22
Issue Fixed

Can i know how this module work? As our requirements is ping a host every second and some host is ping 10 packets every 60 seconds

**Comment by hmmxp** [comment] 2017-10-14 06:27
Hi Frankie,

I tested and found that packet loss is not displaying correctly, after i break the connection. packet loss still showing 0 percent

**Comment by frankiexyz** [comment] 2017-10-14 07:03
Hi,

For the first question, you can create two jobs in your Prometheus configuration and adjust the scrape interval. I am not sure if you can scrape every second but I know you can definitely scrape at least every 15 seconds. This script is a very simple one, basically it run fping, parse the output and expose the metric to Prometheus. 

For the second question, I was wondering if you find the packet loss was zero in Prometheus/Grafana or the curl result itself? As I mentioned before the scrape interval is 60 seconds in your config, if Prometheus scraped the data before you break the connection and you might need to wait maximum one minute to let Prometheus scrape it again.

**Comment by hmmxp** [comment] 2017-10-14 07:03
Question

The Python Script Is Working But Having Some Question

1. How does the script work? 
2. How is the packet loss calculated?
3. How Is The Min, Avg, Max Calculated?
4. How Many Pings Are Sent or How Can We Define It and Interval?

2. If Host Is Down, Script Will Not Work. It Will Show:
curl: (52) Empty reply from server

I think this is not helpful as we cant see packet loss

Thank You

**Comment by frankiexyz** [comment] 2017-10-14 08:05
Hi, 

I think I can fix point 5 and provide more information regarding point 1 and 4. For point 2-3, you can refer to fping.org

Thanks,
Frankie

**Comment by hmmxp** [comment] 2017-10-14 08:22
Hi Frankie,

For Point #1 - Maybe some comment inside the script to understand how the entire code is done?
For Point #4 - My Meaning Inside the Script, Can We Define The Ping Interval?

This project have potential to replace smokeping, but some kinks needs to be ironed out

Awesome Job Bro

**Comment by frankiexyz** [comment] 2017-10-15 05:27
Hi, Just merged https://github.com/frankiexyz/ping-exporter/pull/6
And you can ping with interval now.

**Comment by hmmxp** [comment] 2017-10-15 13:02
Dear Frankie,

Will test tomorrow and provide further feedback.

I will also push this exporter to the public as i believe this script is very useful

Thank You,
Emmanuel

**Comment by hmmxp** [comment] 2017-10-15 23:35
Dear Frankie,

Host 10.62.18.133 is down but using ping-exporter, it is not showing packet loss? Can check?
![image](https://user-images.githubusercontent.com/28424140/31590541-6b4a4584-b244-11e7-84f7-1c939cf1e933.png)

Ping Exporter i am seeing this
![image](https://user-images.githubusercontent.com/28424140/31590553-98de1246-b244-11e7-8c35-c100cd192b8a.png)

Can guide?

Thank You,
Emmanuel

**Comment by frankiexyz** [comment] 2017-10-16 14:17
Hi Emmanuel,
I tried to ping some unreachable destinations and it seems to be working fine. Can you share the output too?
```
HypriotOS/armv7: root@alpha02 in ~
$ ping f.root-servers.net -c 5
PING f.root-servers.net (192.5.5.241) 56(84) bytes of data.

--- f.root-servers.net ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4006ms

HypriotOS/armv7: root@alpha02 in ~
$ curl "127.0.0.1:8085/?target=f.root-servers.net"
ping_avg 0
ping_max 0
ping_min 0
ping_loss 100
```
Thanks,
Frankie

**Comment by frankiexyz** [comment] 2017-10-19 02:42
Hi Emmanuel,

Would you please confirm if there is any outstanding issue? I will close this one otherwise.

Thanks,
Frank

**Closed as completed** 2017-10-20 03:15 UTC
